version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_bank
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bank_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bank-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_bank
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - bank-net

  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth_service
    restart: unless-stopped
    environment:
      PORT: 3001
      DATABASE_URL: postgres://admin:admin@postgres:5432/bank_db
      JWT_SECRET: supersecretjwt
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - bank-net

  account-service:
    build:
      context: ./services/account-service
    container_name: account_service
    restart: unless-stopped
    environment:
      PORT: 3002
      DATABASE_URL: postgres://admin:admin@postgres:5432/bank_db
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    networks:
      - bank-net

  transaction-service:
    build:
      context: ./services/transaction-service
    container_name: transaction_service
    restart: unless-stopped
    environment:
      PORT: 3003
      DATABASE_URL: postgres://admin:admin@postgres:5432/bank_db
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    networks:
      - bank-net

  # OpenTelemetry Collector ser√° adicionado depois
  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:latest
  #   container_name: otel_collector
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #   command: ["--config=/etc/otel-collector-config.yaml"]
  #   ports:
  #     - "4318:4318" # HTTP traces
  #     - "4317:4317" # gRPC traces
  #   networks:
  #     - bank-net

networks:
  bank-net:

volumes:
  postgres_data:
