version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_bank
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bank_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bank-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_bank
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - bank-net

  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth_service
    restart: unless-stopped
    environment:
      PORT: 3001
      DATABASE_URL: postgres://admin:admin@postgres:5432/bank_db
      JWT_SECRET: supersecretjwt
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: auth-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - bank-net

  account-service:
    build:
      context: ./services/account-service
    container_name: account_service
    restart: unless-stopped
    environment:
      PORT: 3002
      DATABASE_URL: postgres://admin:admin@postgres:5432/bank_db
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: account-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    networks:
      - bank-net

  transaction-service:
    build:
      context: ./services/transaction-service
    container_name: transaction_service
    restart: unless-stopped
    environment:
      PORT: 3003
      DATABASE_URL: postgres://admin:admin@postgres:5432/bank_db
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: transaction-service
      ACCOUNT_SERVICE_URL: http://account-service:3002
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    networks:
      - bank-net

  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    networks:
      - bank-net

networks:
    bank-net:

volumes:
  postgres_data: